---
info:
  title: Snipcart API
  description: A tool used to process orders.
  version: '1.0'
paths:
  "/orders":
    get:
      summary: Grab incoming orders
      parameters:
      - name: offset
        in: query
        description: Number of results to skip. Default is 0.
        required: true
        default: 0
        type: integer
      - name: limit
        in: query
        description: Number of results to fetch. Default is 20.
        required: true
        default: 20
        type: integer
      - name: status
        in: query
        description: 'A status criteria for your order collection. Possible values:
          (`InProgress`, `Processed`, `Disputed`, `Shipped`, `Delivered`, `Pending`,
          `Cancelled`)'
        required: false
        enum:
        - inprogress
        - processed
        - disputed
        - shipped
        - delivered
        - pending
        - cancelled
        type: string
      - name: invoiceNumber
        in: query
        description: The invoice number of the order to retrieve.
        required: false
        type: string
      - name: productId
        in: query
        description: Returns only orders containing that product. **Note that this
          has to be the user defined ID, not the unique ID defined by Snipcart
        required: false
        type: string
      - name: placedBy
        in: query
        description: The name of the person who made the purchase.
        required: false
        type: string
      - name: from
        in: query
        description: Returns only the orders placed after this date.
        required: false
        type: string
      - name: to
        in: query
        description: Returns only the orders placed before this date.
        required: false
        type: string
      - name: isRecurringOrder
        in: query
        description: returns only the orders that are recurring or not.
        required: false
        type: boolean
      responses:
        '200':
          description: Everything went well.
          schema:
            type: string
        '201':
          description: Created. A new resource has been created.
        '204':
          description: A new resource has been deleted.
        '400':
          description: The provided information is invalid, the request failed.
        '404':
          description: "  The resource has not been found."
        '500':
          description: Something went wrong on our side.
        '502':
          description: Something went wrong on our side.
        '503':
          description: Something went wrong on our side.
        '504':
          description: Something went wrong on our side.
      security:
      - API_Key: []
      produces:
      - application/json
swagger: '2.0'
host: "localhost:10010"
schemes:
- https
basePath: "/api"
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        description: The user ID.
      username:
        type: string
        description: The user name.
securityDefinitions:
  API_Key:
    type: basic
x-components:
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
      headers:
        WWW_Authenticate:
          style: simple
          explode: false
          schema:
            type: string
  headers:
    schema:
      "$ref": "#/definitions/User"
